import{S as d,N as u}from"./assets/vendor-58205fe0.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const n of e)if(n.type==="childList")for(const i of n.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&r(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const n={};return e.integrity&&(n.integrity=e.integrity),e.referrerPolicy&&(n.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?n.credentials="include":e.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function r(e){if(e.ep)return;e.ep=!0;const n=s(e);fetch(e.href,n)}})();(()=>{const t=document.querySelector(".js-menu-container"),o=document.querySelector(".js-mobile-menu"),s=document.querySelector(".js-open-menu"),r=()=>{const e=t.querySelectorAll('a[href*="#"]'),n=s.getAttribute("aria-expanded")==="true"||!1;s.setAttribute("aria-expanded",!n),t.classList.toggle("is-open"),s.classList.toggle("is-open");const i=n?"enableBodyScroll":"disableBodyScroll";if(bodyScrollLock[i](document.body),e.length!==0){if(!n){e.forEach(a=>{a.addEventListener("click",r)});return}e.forEach(a=>{a.removeEventListener("click",r)})}};s.addEventListener("click",r),t.addEventListener("click",e=>{o.contains(e.target)||r()}),window.matchMedia("(min-width: 1199px)").addEventListener("change",e=>{e.matches&&(t.classList.remove("is-open"),s.classList.toggle("is-open"),s.setAttribute("aria-expanded",!1),bodyScrollLock.enableBodyScroll(document.body))})})();new d(".review-swiper",{modules:[u],breakpoints:{320:{centeredSlides:!0,slidesPerView:"auto",spaceBetween:8},1200:{slidesPerView:3,spaceBetween:4,slidesPerGroup:1}},navigation:{nextEl:".swiper-button-next-reviews",prevEl:".swiper-button-prev-reviews"}});const p=[{question:"How do I play Restaurant Rescue?",answer:"Download the game from the Play Store and start managing your restaurant by cooking and serving dishes."},{question:"Is the game free?",answer:"Yes, the game is free to play, with optional in-app purchases for boosters and upgrades."},{question:"Can I play offline?",answer:"Absolutely! Restaurant Rescue can be played without an internet connection."},{question:"Are there rewards for completing levels?",answer:"Yes! Earn coins, stars, and exclusive items as you progress through the game."},{question:"How often is new content added?",answer:"Regular updates bring new recipes, challenges, and exciting story chapters."}],f="/RestaurantRescue/assets/sprite-aaec932e.svg",g=document.querySelector(".accordion-thumb");function m(){const t=p.map(o=>`<li class="accordion-thumb__item">
        <div class="accordion-wrapper">
          <button class="accordion" type="button">
            <p>${o.question}</p>
            <svg width="28" height="28">
              <use
                class="accordion-toggle-icon"
                href="${f}#icon-accordion-open"
              ></use>
            </svg>
          </button>
          <div class="panel">
            <p>${o.answer}</p>
          </div>
        </div>
      </li>`).join("");g.innerHTML=t}m();const l=document.querySelectorAll(".accordion");c(l[0]);l.forEach(t=>{t.addEventListener("click",h)});function h(){const t=document.querySelector(".accordion[data-expanded]");t&&t!==this&&c(t),c(this)}function c(t){t.classList.toggle("active"),t.dataset.expanded===void 0?t.dataset.expanded="":delete t.dataset.expanded;const o=t.nextElementSibling;o.style.maxHeight?o.style.maxHeight=null:o.style.maxHeight=o.scrollHeight+"px"}
//# sourceMappingURL=commonHelpers.js.map
